package businesslogic;

import domain.ClassInstance;
import domain.Timetable;

import java.util.List;

/**
 * Evaluates and ranks generated timetables based on user-defined scheduling preferences.
 * Adheres to Layer 3 architecture by incorporating PreferenceRanker and ScoringMethod logic.
 */
public class PreferenceEngine {

    private PreferenceRanker ranker;

    public PreferenceEngine() {
        this.ranker = new PreferenceRanker();
    }

    /**
     * Ranks a list of valid, clash-free timetables according to the user's ordered preferences.
     * * @param validTimetables The pool of potential timetables generated by the ScheduleEngine.
     *
     * @param orderedPreferences The user's preferences, ordered from highest to lowest priority.
     * @return A sorted list of timetables, from most optimal (index 0) to least optimal.
     */
    public List<Timetable> rankTimetables(List<Timetable> validTimetables, List<String> orderedPreferences) {
        // Not including preferences is valid. If none are provided, return the unranked list[cite: 56].
        if (orderedPreferences == null || orderedPreferences.isEmpty()) {
            return validTimetables;
        }

        return ranker.rank(validTimetables, orderedPreferences);
    }

    // ===================================================================================
    // INTERNAL ARCHITECTURE COMPONENTS (PreferenceRanker & ScoringMethod)
    // ===================================================================================

    /**
     * Responsible for sorting the timetables based on calculated preference scores.
     */
    private class PreferenceRanker {
        private ScoringMethod scorer = new ScoringMethod();

        public List<Timetable> rank(List<Timetable> timetables, List<String> orderedPreferences) {
            timetables.sort((t1, t2) -> {
                int score1 = scorer.calculateTotalScore(t1, orderedPreferences);
                int score2 = scorer.calculateTotalScore(t2, orderedPreferences);

                // Sort in descending order so the highest score is at the top of the list
                return Integer.compare(score2, score1);
            });
            return timetables;
        }
    }

    /**
     * Responsible for evaluating individual timetables against the specific preference rules.
     */
    private class ScoringMethod {

        public int calculateTotalScore(Timetable timetable, List<String> orderedPreferences) {
            int totalScore = 0;
            // The highest ranked preference receives the highest mathematical weight
            int weight = orderedPreferences.size();

            for (String preference : orderedPreferences) {
                if (evaluatePreference(timetable, preference.toLowerCase().trim())) {
                    totalScore += weight;
                }
                weight--; // Decrement weight for lower-priority preferences
            }
            return totalScore;
        }

        /**
         * Evaluates if a timetable successfully meets a specific preference condition.
         */
        private boolean evaluatePreference(Timetable timetable, String preference) {
            List<ClassInstance> classes = timetable.getScheduledClasses();
            if (classes == null || classes.isEmpty()) return false;

            return switch (preference) {
                case "mornings" -> checkTimePreference(classes, true);
                case "afternoons" -> checkTimePreference(classes, false);
                case "mondays", "tuesdays", "wednesdays", "thursdays", "fridays" ->
                        checkDayPreference(classes, preference);
                case "all at the same campus" -> checkSingleCampus(classes);
                case "compact classes to as few days as possible" -> checkCompactness(classes);
                case "evenly spread classes across days" -> checkEvenSpread(classes);
                // Campus specific preferences
                case "bedford park", "tonsley", "flinders city campus" -> checkSpecificCampus(classes, preference);
                default -> false;
            };
        }

        // --- Evaluation Helper Methods ---

        /**
         * Evaluates if the majority of classes occur in the specified time period.
         */
        private boolean checkTimePreference(List<ClassInstance> classes, boolean isMorning) {
            // Assuming 12:00 (720 minutes) is the threshold between morning and afternoon
            int threshold = 12 * 60;
            int matchCount = 0;

            for (ClassInstance instance : classes) {
                int startMins = parseTimeToMinutes(instance.getStartTime());
                if (isMorning && startMins < threshold) {
                    matchCount++;
                } else if (!isMorning && startMins >= threshold) {
                    matchCount++;
                }
            }
            // Preference is met if more than 50% of the classes align with the requested time
            return matchCount > (classes.size() / 2);
        }

        /**
         * Evaluates if the timetable contains classes on the specific requested day.
         */
        private boolean checkDayPreference(List<ClassInstance> classes, String targetDay) {
            // Normalizing the string by removing the plural 's' (e.g., "mondays" -> "monday")
            String normalizedTarget = targetDay.toLowerCase().replace("s", "");
            for (ClassInstance instance : classes) {
                if (instance.getDay().toLowerCase().contains(normalizedTarget)) {
                    return true;
                }
            }
            return false;
        }

        /**
         * Evaluates if all classes in the timetable are held at the exact same campus.
         */
        private boolean checkSingleCampus(List<ClassInstance> classes) {
            if (classes.isEmpty()) return true;

            String firstCampus = extractCampus(classes.get(0).getBuilding());
            for (ClassInstance instance : classes) {
                if (!extractCampus(instance.getBuilding()).equalsIgnoreCase(firstCampus)) {
                    return false; // Found a class at a different campus
                }
            }
            return true;
        }

        /**
         * Evaluates if the majority of classes are held at the specifically requested campus.
         */
        private boolean checkSpecificCampus(List<ClassInstance> classes, String targetCampus) {
            int matchCount = 0;
            for (ClassInstance instance : classes) {
                if (extractCampus(instance.getBuilding()).equalsIgnoreCase(targetCampus.trim())) {
                    matchCount++;
                }
            }
            return matchCount > (classes.size() / 2);
        }

        /**
         * Evaluates if the timetable is compact (occupies 2 or fewer unique days).
         */
        private boolean checkCompactness(List<ClassInstance> classes) {
            return countUniqueDays(classes) <= 2;
        }

        /**
         * Evaluates if the timetable is evenly spread (occupies 4 or more unique days).
         */
        private boolean checkEvenSpread(List<ClassInstance> classes) {
            return countUniqueDays(classes) >= 4;
        }

        // --- Internal Data Parsing Utility Methods ---

        /**
         * Converts a HH:mm string into total minutes for mathematical comparison.
         */
        private int parseTimeToMinutes(String time) {
            try {
                String[] parts = time.split(":");
                return (Integer.parseInt(parts[0].trim()) * 60) + Integer.parseInt(parts[1].trim());
            } catch (Exception e) {
                return 0; // Fallback for malformed time data
            }
        }

        /**
         * Extracts the broad campus identifier from a specific building string.
         */
        private String extractCampus(String location) {
            if (location == null) return "";
            String locLower = location.toLowerCase();

            if (locLower.contains("tonsley")) return "tonsley";
            if (locLower.contains("bedford")) return "bedford park";
            if (locLower.contains("city") || locLower.contains("festival tower")) return "flinders city campus";

            // Fallback: assume the first part of the string before a comma is the campus
            return location.split(",")[0].trim();
        }

        /**
         * Calculates the number of unique days utilized in the timetable.
         */
        private long countUniqueDays(List<ClassInstance> classes) {
            return classes.stream()
                    .map(c -> c.getDay().toLowerCase().trim())
                    .distinct()
                    .count();
        }
    }
}